accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserViewSet, login_api, register_api, logout_api

app_name = 'accounts'

router = DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    # Custom registration view
    path("register/", views.register, name="register"),
    path('login/', views.loginPage, name="login"),
    path('', views.loginPage, name="login"),

    # Django's built-in authentication views
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/accounts/login/"), name="logout"),
    path('password-change/', views.ChangePasswordView.as_view(),
         name='password_change'),
    path('password-reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    
    
    path('api/', include(router.urls)),
    path('api/login/', login_api, name='api-login'),
    path('api/register/', register_api, name='api-register'),
    path('api/logout/', logout_api, name='api-logout'),

]

etimsx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),  # Add this line
    path("", include("accounts.urls")),  # Add this line

    # Include each app's URLs under its own unique prefix
    path('api/organization/', include('organization.urls')),  # organization URLs
    path('api/device/', include('device.urls')),  # organization URLs
    path('api/item/', include('item.urls')),                  # item URLs
    path('api/customer/', include('customer.urls')),          # customer URLs
    path('api/transaction/', include('transaction.urls')),    # transaction URLs
    path('api/item_movement/', include('item_movement.urls')),  # inventory URLs
    path('api/sales_items/', include('sales_items.urls')),    # sales_items URLs
    path("select2/", include("django_select2.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name = 'item'  # This is the namespace

urlpatterns = [
    path("", views.item_list, name="item_list"),
    path("create/<int:pk>/", views.item_create, name="item_create"),
    path("<int:pk>/", views.item_detail, name="item_detail"),
    path("<int:pk>/update/", views.item_update, name="item_update"),
    path("<int:pk>/delete/", views.item_delete, name="item_delete"),
    path('update-quantity/', views.update_item_quantity, name='update_quantity'),
    path('update_mapped_item_quantity/', views.update_mapped_item_quantity,
         name='update_mapped_item_quantity'),
    path('create_items_from_purchase/<int:pk>/', views.create_items_from_purchase,
         name='create_items_from_purchase'),
    path("save-item-composition/", views.save_item_composition,
         name="save_item_composition"),
    path('ajax/filter/<str:field_name>/',
         views.ajax_filter, name='ajax_filter'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CustomUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email').lower()
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("A user with this email or username already exists.")
        return email

    def clean_username(self):
        username = self.cleaned_data.get('username').lower()
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("A user with this email or username already exists.")
        return username

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from .forms import CustomUserForm
from django.contrib import messages
from .emails import send_welcome_resident, send_welcome_email
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView, PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404, HttpResponse
from django.contrib.auth.models import User
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.decorators import action, api_view, permission_classes
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.authtoken.models import Token
from django.shortcuts import get_object_or_404
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .serializers import UserSerializer, LoginSerializer, RegisterSerializer
from organization.views import *



@login_required(login_url='login')
def home(request):
    user = request.user

    # Check if user is authenticated
    if user.is_authenticated:
        return redirect('organization:organization_list')  # Redirect to organization_list if user is logged in
    else:
        raise Http404("User not found")  # Raise a 404 error for unauthorized access


def loginPage(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('organization:organization_list')

    if request.method == 'POST':
        username = request.POST.get("username").lower()
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('organization:organization_list')
        else:
            messages.error(request, 'Invalid username or Password')

    context = {'page': page}
    return render(request, 'accounts/register.html', context)


@login_required(login_url='login')
def logoutUser(request):
    logout(request)
    return redirect(loginPage)

# END USER || ADMIN

# ADMIN SECTION


def register(request):
    if request.user.is_authenticated:
        logout(request)

    if request.method == 'POST':
        form = CustomUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.email = user.email.lower()
            user.first_name = user.first_name.lower()
            user.last_name = user.last_name.lower()
            user.save()

            # User.objects.create(user=user)

            try:
                email = user.email
                name = user.username
                send_welcome_email(name, email)
                login(request, user)
                return redirect('organization:organization_list')
            except:
                login(request, user)
                return redirect('organization:organization_list')
        else:
            messages.error(request, 'please try again')
    else:
        form = CustomUserForm()

    context = {'form': form}
    return render(request, 'accounts/register.html', context)


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'accounts/change_password.html'
    success_message = "Successfully Changed Your Password"
    # success_url = reverse_lazy(residentDashboard)


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'accounts/password_reset.html'
    email_template_name = 'accounts/password_reset_email.html'
    subject_template_name = 'accounts/password_reset_subject.txt'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('accounts:login')
    

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = [IsAuthenticated]

    @action(detail=False, methods=['get'])
    def me(self, request):
        serializer = self.get_serializer(request.user)
        return Response(serializer.data)

@api_view(['POST'])
@permission_classes([AllowAny])
def login_api(request):
    serializer = LoginSerializer(data=request.data)
    if serializer.is_valid():
        username = serializer.validated_data['username']
        password = serializer.validated_data['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            token, created = Token.objects.get_or_create(user=user)  # Ensure Token is imported
            return Response({"token": token.key, "user": UserSerializer(user).data})
        return Response({"error": "Invalid credentials"}, status=status.HTTP_401_UNAUTHORIZED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
@permission_classes([AllowAny])
def register_api(request):
    serializer = RegisterSerializer(data=request.data)
    if serializer.is_valid():
        user = serializer.save()
        token, created = Token.objects.get_or_create(user=user)
        return Response({"token": token.key, "user": UserSerializer(user).data}, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def logout_api(request):
    request.user.auth_token.delete()
    logout(request)
    return Response({"message": "Logged out successfully"}, status=status.HTTP_200_OK)

accounts/templates/accounts/change_password.html
{% extends 'main.html' %}
{% load bootstrap5 %}

{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_old_password">Old Password</label>
                                                <input type="password" name="old_password" autocomplete="new-password"
                                                       class="form-control" required id="id_old_password"
                                                       placeholder="Enter Old Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter New Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm New Password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Update Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/login.html
<form method="post">
    {% csrf_token %}
    <h2>Login</h2>
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
<p><a href="{% url 'accounts:register' %}">Register Account</a></p>
<p><a href="{% url 'accounts:password_reset' %}">Forgot Password?</a></p>

accounts/templates/accounts/logout.html
<p>You have been logged out. <a href="{% url 'accounts:login' %}">Login again?</a></p>

accounts/templates/accounts/password_reset.html
{% extends 'main.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="form-content my-3 p-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="card-header justify-content-center">
                        <div id="error_div"></div>
                        <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                    </div>
                    {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <div id="form_errors">
                            {% for key, value in form.errors.items %}
                            <strong>{{ value }}</strong>
                            {% endfor %}
                        </div>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                        <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email" class="form-control" autocomplete="email"
                                            maxlength="254" required id="id_email" placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small">
                            <a href="{% url 'accounts:register' %}" >Create A New Account</a><br><br>
                            <a href="{% url 'accounts:login' %}">Back To Login</a><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'main.html' %}
{% load bootstrap5 %}

{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Neighbourhoodx Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  Lyons 
{% endautoescape %}

accounts/templates/accounts/register.html
{% extends 'main.html' %}
{% block content %}
{% load static %}
{% load bootstrap5 %}
{% include 'nav.html' %}

<div class="container-fluid bgx">

    {% if page == 'login' %}

    <div class="l-gx" style="min-width:30rem;">
        <div class="container">
            <div class="form-data">
                <form action="" method="post" class="fm ressx">
                    {% csrf_token %}
                    <div class="dix">
                        <div class="form__group">
                            <label for="" class="fm">Username:</label>
                            <input type="text" name="username" id="" placeholder="Enter Username" required>
                        </div>
                        <p></p>
                        <div class="form__group">
                            <label for="" class="fm">Password:</label>
                            <input type="password" name="password" id="" placeholder="Enter password" required>

                        </div>
                        {% for message in messages %}
                        <div class="message-err">
                            <li class="">{{message}}</li>
                        </div>
                        {% endfor %}
                    </div>
                    <p class="text-center text-white mb-5">
                        <input type="submit" value="Login" class="btn btn--main sl text-white"
                            style="width: max-content;">
                    </p>
                    <span class="has-separator text-center text-black"> - - - - - - - - &nbsp; OR &nbsp; - - - - - - - -
                    </span>
                    <div class="sign-up text-black">
                        Already have an account? <a href="{% url 'accounts:register' %}" class="btn sd"> Sign Up </a>
                    </div>
                    <a href="{% url 'accounts:password_reset' %}" class="text-center text-black password-reset">Forgot
                        password?</a>

                </form>
            </div>
        </div>
    </div>

    {% else %}

    <div class="l-gx" style="min-width:30rem;">
        <div class="container">
            <div class="form-data">
                <form action="" method="post" class="fm ressx">
                    {% csrf_token %}
                    <div class="dix">
                        {% for field in form %}
                        <div class="form__group">
                            <label for="field_name">{{field.label}}</label>
                            {{field}}
                        </div>
                        {% endfor %}
                        {% for message in messages %}
                        <div class="message-err">
                            <li class="">{{message}}</li>
                        </div>
                        {% endfor %}

                    </div>
                    <p class="text-center">
                        <button type="submit" class="btn sd" style="width: max-content;">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                viewBox="0 0 32 32">
                                <title>lock</title>
                                <path
                                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z">
                                </path>
                                <path
                                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z">
                                </path>
                            </svg>
                            Sign Up
                        </button>
                    </p>
                    <div class="sign-up text-black">
                        Already have an account? <a href="{% url 'accounts:login' %}" class="btn sd"> Login </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endif %}

{% endblock content %}