accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserViewSet, login_api, register_api, logout_api

app_name = 'accounts'

router = DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    # Custom registration view
    path("register/", views.register, name="register"),
    path('login/', views.loginPage, name="login"),
    path('', views.loginPage, name="login"),

    # Django's built-in authentication views
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/accounts/login/"), name="logout"),
    path('password-change/', views.ChangePasswordView.as_view(),
         name='password_change'),
    path('password-reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    
    
    path('api/', include(router.urls)),
    path('api/login/', login_api, name='api-login'),
    path('api/register/', register_api, name='api-register'),
    path('api/logout/', logout_api, name='api-logout'),

]

etimsx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),  # Add this line
    path("", include("accounts.urls")),  # Add this line

    # Include each app's URLs under its own unique prefix
    path('api/organization/', include('organization.urls')),  # organization URLs
    path('api/device/', include('device.urls')),  # organization URLs
    path('api/item/', include('item.urls')),                  # item URLs
    path('api/customer/', include('customer.urls')),          # customer URLs
    path('api/transaction/', include('transaction.urls')),    # transaction URLs
    path('api/item_movement/', include('item_movement.urls')),  # inventory URLs
    path('api/sales_items/', include('sales_items.urls')),    # sales_items URLs
    path("select2/", include("django_select2.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name = 'item'  # This is the namespace

urlpatterns = [
    path("", views.item_list, name="item_list"),
    path("create/<int:pk>/", views.item_create, name="item_create"),
    path("<int:pk>/", views.item_detail, name="item_detail"),
    path("<int:pk>/update/", views.item_update, name="item_update"),
    path("<int:pk>/delete/", views.item_delete, name="item_delete"),
    path('update-quantity/', views.update_item_quantity, name='update_quantity'),
    path('update_mapped_item_quantity/', views.update_mapped_item_quantity,
         name='update_mapped_item_quantity'),
    path('create_items_from_purchase/<int:pk>/', views.create_items_from_purchase,
         name='create_items_from_purchase'),
    path("save-item-composition/", views.save_item_composition,
         name="save_item_composition"),
    path('ajax/filter/<str:field_name>/',
         views.ajax_filter, name='ajax_filter'),
]

organization/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'organization'  # This is the namespace


# router = DefaultRouter()
# router.register(r'organizations', views.OrganizationViewSet)

urlpatterns = [
    path("", views.organization_list, name="organization_list"),
    path("create/", views.organization_create, name="organization_create"),
    path("<int:pk>/", views.organization_detail, name="organization_detail"),
    path("<int:pk>/update/", views.organization_update,
         name="organization_update"),
    path("<int:pk>/delete/", views.organization_delete,
         name="organization_delete"),
    path('download-invoice/<int:pk>/',
         views.download_invoice, name='download_invoice'),
    path("retry/<str:request_type>/<int:request_id>/",
         views.retry_failed_request, name="retry_failed_request"),
    path("update_purchases_view/<int:org_id>/",
         views.update_purchases_view, name="update_purchases_view"),
    path("verify/<str:request_type>/<str:inv_no>/<int:purchase_id>",
         views.verify_purchase, name="verify_purchase"),
    path("update_imports_view/<int:org_id>/",
         views.update_imports_view, name="update_imports_view"),
    #     path("verify/<str:request_type>/<str:inv_no>/<int:import_id>",
    #          views.verify_import, name="verify_import"),
    path('settings/<int:organization_id>/',
         views.organization_settings, name='organization_settings'),
    path('initialize-device/', views.initialize_device_view,
         name='initialize_device'),
    path('update-classifications/', views.fetch_classifications_view,
         name='fetchItemClassification'),
    path('update-tax_codes/', views.fetch_tax_codes_view,
         name='fetchTaxCodes'),
    path('update-branches/', views.update_branches_view,
         name='fetchBranches'),
    path('update-notices/', views.update_notices_view,
         name='fetchNotices'),
    path('update-imports/', views.fetch_imports_view, name='fetchImports'),

    #     path('api/', include(router.urls)),
    #     path('api/retry/<str:request_type>/<int:request_id>/', views.retry_failed_request, name='api-retry-failed-request'),
    #     path('api/update_purchases/<int:org_id>/', views.update_purchases_view, name='api-update-purchases'),
    #     path('api/verify/<str:request_type>/<str:inv_no>/<int:purchase_id>/', views.verify_purchase, name='api-verify-purchase'),

]

templates/invoice_tempate.html
<!DOCTYPE html>
<html style="min-width: 100vw; min-height: 90vh;">

<head>
    <title>Invoice</title>
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }

        .invoice-container {
            width: 100vw;
            min-height: 100vh;
            margin: 0 0;
            background: #fff;
            padding: 0px;
            display: flex;
            justify-content: space-between;
            flex-direction: column;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 3px solid #083613;
            padding-bottom: 40px;
        }

        .header .company-info {
            font-size: 0.9rem;
            color: #555;
        }

        .header img {
            height: 50px;
        }

        .invoice-details {
            margin-top: 30px;
            display: flex;
            justify-content: space-between;
            font-size: 0.9rem;
        }

        .section {
            width: 48%;
        }

        .section h4 {
            margin: 0 0 5px;
            color: #083613;
        }

        .section p {
            margin: 5px 0;
            color: #555;
        }

        .invoice-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 40px;
        }

        .invoice-table th,
        .invoice-table td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }

        .invoice-table th {
            background-color: #083613;
            color: #fff;
        }

        .invoice-table tbody tr:nth-child(odd) {
            background-color: #f1f1f1;
        }

        .summary {
            margin-top: 30px;
            text-align: right;
        }

        .summary strong {
            font-size: 1.1rem;
        }

        .tax-summary-table {
            width: 100%;
            font-weight: 500;
            border-collapse: collapse;
            margin-top: 100px;
            font-size: 13px;
            text-align: left;
        }

        .tax-summary-table th,
        .tax-summary-table td {
            font-weight: 500;
            padding: 8px;
        }

        .tax-summary-table th {
            background-color: #f9f9f9;
            text-align: left;
        }

        .tax-summary-table td {
            text-align: left;
        }

        .tax-summary-table tr:hover {
            background-color: #e9ecef;
        }

        .tax-summary-table td:first-child {
            text-align: left;
        }

        footer {
            margin-top: 100px;
            text-align: center;
            font-size: 0.8rem;
            color: #555;
        }
    </style>
</head>

<body>
    <div class="invoice-container">
        <div class="upper">
            <div class="header">
                <div class="company-info">
                    <p><strong>{{ organization.organization_name }}</strong></p>
                    <p>{{ organization.organization_physical_address}}</p>
                    <p>VAT Registration No. {{organization.organization_pin}}</p>
                </div>
                <img src="{{ qrcode_path }}" alt="Etims Logo">

            </div>

            <div class="invoice-details">
                <div class="section">
                    <h4>Bill To</h4>
                    <p><strong>{{ customer_name }}</strong></p>
                    <p>{{ customer_email }}</p>
                    <p>KRA Pin No. {{ customer_pin }}</p>
                </div>
                <div class="section">
                    <h4>{{ document_type }} Details</h4>
                    <p><strong>{{ document_type }} No:</strong> {{ document_number }}</p>
                    <p><strong>Date:</strong> {{ document_date }}</p>
                </div>
            </div>

            <table class="invoice-table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Item</th>
                        <th>Description</th>
                        <th>Quantity</th>
                        <th>Rate</th>
                        <th>Discount</th>
                        <th>Line Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ item.name }}</td>
                        <td>{{ item.description }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.rate }}</td>
                        <td>{{ item.discount }}</td>
                        <td>{{ item.line_total }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="summary">
                <p><strong>Total Amount:</strong> <span id="total-due" style="color: #083613;">Ksh {{total_due}}</span>
                </p>
            </div>
        </div>

        <table class="tax-summary-table">
            <thead>
                <tr>
                    <th>Tax Class</th>
                    <th>A-Exempt</th>
                    <th>B-VAT 16%</th>
                    <th>C-Zero Rated</th>
                    <th>E-VAT 8%</th>
                    <th>D-Non VAT</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Taxable Amount (KES)</td>
                    <td>{{ tax_summary.A.taxable_amount|floatformat:2 }}</td>
                    <td>{{ tax_summary.B.taxable_amount|floatformat:2 }}</td>
                    <td>{{ tax_summary.C.taxable_amount|floatformat:2 }}</td>
                    <td>{{ tax_summary.E.taxable_amount|floatformat:2 }}</td>
                    <td>{{ tax_summary.D.taxable_amount|floatformat:2 }}</td>
                </tr>
                <tr>
                    <td>Tax Rate (%)</td>
                    <td>{{ tax_summary.A.tax_rate }}</td>
                    <td>{{ tax_summary.B.tax_rate }}</td>
                    <td>{{ tax_summary.C.tax_rate }}</td>
                    <td>{{ tax_summary.E.tax_rate }}</td>
                    <td>{{ tax_summary.D.tax_rate }}</td>
                </tr>
                <tr>
                    <td>Tax Amount (KES)</td>
                    <td>{{ tax_summary.A.tax_amount|floatformat:2 }}</td>
                    <td>{{ tax_summary.B.tax_amount|floatformat:2 }}</td>
                    <td>{{ tax_summary.C.tax_amount|floatformat:2 }}</td>
                    <td>{{ tax_summary.E.tax_amount|floatformat:2 }}</td>
                    <td>{{ tax_summary.D.tax_amount|floatformat:2 }}</td>
                </tr>
            </tbody>
        </table>

        <footer>
            Thank you for your business. For inquiries, contact us at {{organization.organization_email}}
        </footer>
    </div>

</body>

</html>

templates/invoice_template.html
{% load template_filters %}

<!DOCTYPE html>
<html style="min-width: 100vw; min-height: 100vh;">

<head>
    <title>Invoice</title>
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            backgrousnd-color: #f9f9f9;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        .invoice-container {
            width: 100vw;
            min-height: 100vh;
            margin: 0 0;
            padding: 0px;
            display: flex;
            justify-content: space-between;
            flex-direction: column;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 0.01rem solid #000000;
            padding-bottom: 10px;
        }

        .header .company-info {
            font-size: 0.9rem;
            padding: 0rem;
            color: #000000;
        }

        .company-info p {
            padding: 0rem;
        }

        .header img {
            height: 115px;
        }

        .invoice-details {
            margin-top: 30px;
            width: 100vw !important;
            display: flex;
            justify-content: space-between;
            font-size: 0.9rem;
        }

        .section h4 {
            margin: 0 0 5px;
            color: #000000;
        }

        .section p {
            margin: 5px 0;
            color: #000000;
        }

        .invoice-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 30px;
        }

        .invoice-table th,
        .invoice-table td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }

        .invoice-table th {
            background-color: #f9f9f9;
        }

        .invoice-table tbody tr:nth-child(odd) {
            background-color: #f1f1f1;
        }

        .summary {
            margin-top: 30px;
            text-align: right;
        }

        .summary strong {
            font-size: 1.1rem;
        }

        .tax-summary-table {
            width: 100%;
            font-weight: 500;
            border-collapse: collapse;
            margin-top: 100px;
            font-size: 13px;
            text-align: left;
        }

        .tax-summary-table th,
        .tax-summary-table td {
            font-weight: 500;
            padding: 8px;
        }

        .tax-summary-table th {
            background-color: #f9f9f9;
            text-align: left;
        }

        .tax-summary-table td {
            text-align: left;
        }

        .tax-summary-table tr:hover {
            background-color: #e9ecef;
        }

        .tax-summary-table td:first-child {
            text-align: left;
        }

        footer {
            margin-top: 100px;
            text-align: center;
            font-size: 0.8rem;
            color: #464646;
        }
    </style>
</head>

<body>
    <div class="invoice-container">
        <div class="upper">
            <div class="header">
                <div class="company-info">
                    <p style="padding: 0rem; margin: 0rem; margin-bottom: 5px;"><strong>
                            {{organization.organization_name}}</strong></p>
                    <p style="padding: 0rem; margin: 0rem; margin-bottom: 7px">
                        {{organization.organization_physical_address}}</p>
                    <p style="padding: 0rem; margin: 0rem; margin-top: 5px;"><strong>VAT Registration No.</strong>
                        {{organization.organization_pin}}</p>
                </div>
                <img src="{{ qr_code_path }}" alt="{{ qr_code_path }}">
            </div>

            <div class="invoice-details">
                <div class="section">
                    <h4>Bill To</h4>
                    <p><strong>{{ customer_name }}</strong></p>
                    <p>{{ customer_email }}</p>
                    <p><strong>KRA Pin No. </strong>{{ customer_pin }}</p>
                </div>
                <div class="section" style="align-items: flex-end; margin-right: 70px;">
                    <h4>{{ document_type }} Details</h4>
                    <p><strong>{{ document_type }} No. </strong> {{ document_number }}</p>
                    <p><strong>Date:</strong> {{ document_date|date:"d-m-Y" }}</p>
                </div>
            </div>

            <table class="invoice-table">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Description</th>
                        <th>Quantity</th>
                        <th>Rate</th>
                        <th>Discount</th>
                        <th>Total (Tax Code)</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>{{ item.description }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.rate }}</td>
                        <td>{{ item.discount }}</td>
                        <td>{{ item.line_total }} ({{ item.tax_code }})</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="summary">
                <p>Total Amount: <span id="total-due" style="color: #000000;"><strong>Ksh {{total_due}}</strong></span>
                </p>
            </div>
        </div>

        <table class="tax-summary-table">
            <thead>
                <tr>
                    <th>Tax Class</th>
                    <th>A-Exempt</th>
                    <th>B-VAT 16%</th>
                    <th>C-Zero Rated</th>
                    <th>E-VAT 8%</th>
                    <th>D-Non VAT</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Taxable Amount (KES)</td>
                    <td>{{ tax_summary.A.taxable_amount }}</td>
                    <td>{{ tax_summary.B.taxable_amount }}</td>
                    <td>{{ tax_summary.C.taxable_amount }}</td>
                    <td>{{ tax_summary.E.taxable_amount }}</td>
                    <td>{{ tax_summary.D.taxable_amount }}</td>
                </tr>
                <tr>
                    <td>Tax Rate (%)</td>
                    <td>{{ tax_summary.A.tax_rate }}</td>
                    <td>{{ tax_summary.B.tax_rate }}</td>
                    <td>{{ tax_summary.C.tax_rate }}</td>
                    <td>{{ tax_summary.E.tax_rate }}</td>
                    <td>{{ tax_summary.D.tax_rate }}</td>
                </tr>
                <tr>
                    <td>Tax Amount (KES)</td>
                    <td>{{ tax_summary.A.tax_amount }}</td>
                    <td>{{ tax_summary.B.tax_amount }}</td>
                    <td>{{ tax_summary.C.tax_amount }}</td>
                    <td>{{ tax_summary.E.tax_amount }}</td>
                    <td>{{ tax_summary.D.tax_amount }}</td>
                </tr>
            </tbody>
        </table>

    </div>

    <!-- Footer -->
    <footer>
        <p>
            Date: {{ res_date|date:"d-m-Y" }} &nbsp;&nbsp;&nbsp;&nbsp; Time: {{ res_date|date:"H:i:s" }}
        </p>
        <p>SCU ID: {{ receipt_signature }}</p>
        <p>CU Invoice No: {{ receipt_signature }}/{{ receipt_number }}</p>
        <p>Internal Data: {{ internal_data|wordwrap:4 }}</p>
        <br>
        <hr style="color: #c4c4c4; height: 1px;">
        <p>Thank you for your business. For inquiries, contact us at
            <a style="text-decoration: none;" href="">{{ organization.organization_email}}</a>.
        </p>
    </footer>
</body>

</html>

templates/main.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css"
        integrity="sha512-10/jx2EXwxxWqCLX/hHth/vu2KY3jCF70dCQB8TSgNjbCVAC/8vai53GfMDrO2Emgwccf2pJqxct9ehpzG+MTw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Add these to your base template or in your item creation template -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
   
    <link href="{% static 'django_select2/django_select2.css' %}" rel="stylesheet">
    <script src="{% static 'django_select2/django_select2.js' %}"></script>

    <title>EtimsX</title>
    <link rel="icon" href="{% static 'images/default.png' %}" />


    {% block style %}
    {% bootstrap_css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% endblock style %}

</head>

<body>
    {% block content %}


    {% endblock content %}
    {% block scripts %}
    
   
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
        </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
        </script>
    {% bootstrap_javascript %}
    <script src="{% static 'js/main.js' %}"></script>
    {% endblock scripts%}
</body>

</html>

templates/nav.html
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <!-- Application Name -->
            <a class="navbar-brand logo" href="#">Etims Helper</a>

            <!-- Responsive Navbar Toggler -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
                aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav ms-auto">
                    <!-- Profile Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-circle" style="font-size: 1.1rem;"></i> <span>
                    <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a></li></span>
                    </a>

                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

templates/res_nav.html
<nav class="navbar navbar-expand-lg navcolor">
    <div class="container-fluid navbar-x">
        <a href="{% url 'organization:organization_list' %}" class="nav-a" style="color: #00251D !important">
            <h1 class="navlogo">
                Etims Helper
            </h1>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 bg-tr mr-3">
                <div class="d-flex"> </div>
                <li class="nav-item"></li>
                <li class="nav-item">
                    <a href="{% url 'organization:organization_list' %}" class="nav-a"
                        style="color: #00251D !important">
                        <h1 class="navlogo">
                            All Organizations
                        </h1>
                    </a>
                </li>


                {% if organization.id %}
                <li class="nav-item">
                    <a href="{% url 'organization:organization_detail' organization.id %}" class="nav-a"
                        style="color: #00251D !important">
                        <h1 class="navlogo">
                            {{organization.organization_name }}
                        </h1>
                    </a>
                </li>
                {% endif %}


                <li class="nav-item dropdown" ">
                    <a class=" nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false" style="color: white !important;">
                    {% if request.user.profile %}
                    <img src=" {{ request.user.username}}" class="rounded-circle z-depth-0" style="max-width:100%;
                            max-height:100%;">
                    {% else %}
                    <i class="fa fa-user-circle"></i>&nbsp;{{request.user.username}}
                    {%endif%}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item">view profile</a></li>
                        <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
        </div>
    </div>
</nav>